/*
 * YouTubeInitPlayback 1.1.1 — local YouTube iOS initplayback ad negotiation cleanup.
 *
 * Validates the cached key, authenticates and decrypts the encrypted inner
 * player request locally, removes ad negotiation, then re-encrypts and signs
 * it.  A stale/mismatched key clears the cache and returns one empty protobuf
 * response so YouTube refreshes its config.  No URL, key or request body is
 * sent to a third-party service.  YouTube Music is untouched.
 */
(function () {
  "use strict";

  var VERSION = "1.1.1";
  var SOURCE = "YouTubeInitPlayback";
  var STATE_KEY = "ytads.onesie.youtube.v1";
  var LOG_CONFIG = "ytads.logger.config.v1";
  var LOG_CACHE = "ytads.logger.entries.v2";
  var MAX_BODY = 2097152;
  var MAX_FIELDS = 30000;
  var args = typeof $argument === "object" && $argument ? $argument : {};
  var enabled = args.onesie_enabled !== false && args.onesie_enabled !== "false";
  var refreshMismatch = args.onesie_refresh_on_mismatch !== false && args.onesie_refresh_on_mismatch !== "false";
  var debug = flag(args.script_debug);
  var API = /^https:\/\/[a-z0-9-]+\.googlevideo\.com\/initplayback(?:\?[^#]*)?$/i;

  function flag(value) { return value === true || value === "true"; }
  function fail(code) { var error = new Error(code); error.ytNoAdsCode = code; throw error; }
  function bytesOf(value) { if (value instanceof Uint8Array) return value; if (value instanceof ArrayBuffer) return new Uint8Array(value); if (ArrayBuffer.isView(value)) return new Uint8Array(value.buffer,value.byteOffset,value.byteLength); return null; }
  function header(headers, name) { var keys = Object.keys(headers || {}), lower = name.toLowerCase(); for (var i = 0; i < keys.length; i++) if (keys[i].toLowerCase() === lower) return String(headers[keys[i]] || ""); return ""; }
  function isYouTubeApp() { var ua = header($request.headers,"user-agent"); return /(?:^|\s)com\.google\.ios\.youtube\//i.test(ua) && !/youtubemusic/i.test(ua); }
  function readVarint(bytes,cursor) { var value=0,factor=1,count=0; while(cursor.pos<bytes.length&&count++<10){var current=bytes[cursor.pos++];value+=(current&127)*factor;if(!Number.isSafeInteger(value))fail("unsafe-varint");if(current<128)return value;factor*=128;}fail("invalid-varint"); }
  function skipValue(bytes,cursor,no,wire,budget){if(wire===0)readVarint(bytes,cursor);else if(wire===1)cursor.pos+=8;else if(wire===2){var length=readVarint(bytes,cursor);if(!Number.isSafeInteger(length)||length<0||length>bytes.length-cursor.pos)fail("truncated-field");cursor.pos+=length;}else if(wire===3){while(cursor.pos<bytes.length){if(++budget.fields>MAX_FIELDS)fail("field-limit");var tag=readVarint(bytes,cursor),childNo=Math.floor(tag/8),childWire=tag&7;if(!childNo)fail("invalid-tag");if(childWire===4){if(childNo!==no)fail("mismatched-end-group");return;}skipValue(bytes,cursor,childNo,childWire,budget);}fail("truncated-group");}else if(wire===4)fail("unexpected-end-group");else if(wire===5)cursor.pos+=4;else fail("unsupported-wire");if(cursor.pos>bytes.length)fail("truncated-field");}
  function parse(bytes,budget) { var cursor={pos:0},records=[]; while(cursor.pos<bytes.length){if(++budget.fields>MAX_FIELDS)fail("field-limit");var start=cursor.pos,tag=readVarint(bytes,cursor),no=Math.floor(tag/8),wire=tag&7;if(!no)fail("invalid-tag");var dataStart=cursor.pos,dataEnd=cursor.pos,value=null;if(wire===0){value=readVarint(bytes,cursor);dataEnd=cursor.pos;}else if(wire===1){cursor.pos+=8;dataEnd=cursor.pos;}else if(wire===2){var length=readVarint(bytes,cursor);if(!Number.isSafeInteger(length)||length<0||length>bytes.length-cursor.pos)fail("truncated-field");dataStart=cursor.pos;cursor.pos+=length;dataEnd=cursor.pos;}else if(wire===3){skipValue(bytes,cursor,no,wire,budget);dataEnd=cursor.pos;}else if(wire===5){cursor.pos+=4;dataEnd=cursor.pos;}else fail(wire===4?"unexpected-end-group":"unsupported-wire");if(cursor.pos>bytes.length)fail("truncated-field");records.push({no:no,wire:wire,start:start,end:cursor.pos,dataStart:dataStart,dataEnd:dataEnd,value:value});}return records; }
  function only(records,no,wire){var found=null;for(var i=0;i<records.length;i++)if(records[i].no===no&&records[i].wire===wire){if(found)fail("duplicate-schema-field");found=records[i];}return found;}
  function encryptedClientKey(body){var root=bytesOf(body);if(!root||!root.length||root.length>MAX_BODY)fail("unsupported-body");var budget={fields:0},outer=only(parse(root,budget),3,2);if(!outer)return null;var inner=root.subarray(outer.dataStart,outer.dataEnd),key=only(parse(inner,budget),5,2);return key?inner.subarray(key.dataStart,key.dataEnd):null;}
  function base64(bytes){var alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",result="";for(var i=0;i<bytes.length;i+=3){var a=bytes[i],b=i+1<bytes.length?bytes[i+1]:0,c=i+2<bytes.length?bytes[i+2]:0;result+=alphabet[a>>2]+alphabet[((a&3)<<4)|(b>>4)]+(i+1<bytes.length?alphabet[((b&15)<<2)|(c>>6)]:"=")+(i+2<bytes.length?alphabet[c&63]:"=");}return result;}
  function unbase64(text){var alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",clean=String(text||"").replace(/\s+/g,""),out=[];if(!clean||clean.length%4)fail("invalid-base64");for(var i=0;i<clean.length;i+=4){var a=alphabet.indexOf(clean[i]),b=alphabet.indexOf(clean[i+1]),c=clean[i+2]==="="?-1:alphabet.indexOf(clean[i+2]),d=clean[i+3]==="="?-1:alphabet.indexOf(clean[i+3]);if(a<0||b<0||(c<0&&clean[i+2]!=="=")||(d<0&&clean[i+3]!=="=")||(c<0&&d>=0)||(i+4<clean.length&&(c<0||d<0)))fail("invalid-base64");out.push((a<<2)|(b>>4));if(c>=0)out.push(((b&15)<<4)|(c>>2));if(d>=0)out.push(((c&3)<<6)|d);}return new Uint8Array(out);}
  function varint(value){var result=[];do{var byte=value%128;value=Math.floor(value/128);result.push(byte+(value?128:0));}while(value);return new Uint8Array(result);}
  function concat(parts){var size=0,offset=0,i;for(i=0;i<parts.length;i++)size+=parts[i].length;var output=new Uint8Array(size);for(i=0;i<parts.length;i++){output.set(parts[i],offset);offset+=parts[i].length;}return output;}
  function message(no,payload){return concat([varint(no*8+2),varint(payload.length),payload]);}
  function scalar(no,value){return concat([varint(no*8),varint(value)]);}
  function raw(bytes,record){return bytes.subarray(record.start,record.end);}
  function utf8Decode(bytes){if(typeof TextDecoder!=="undefined")return new TextDecoder("utf-8",{fatal:true}).decode(bytes);var text="";for(var i=0;i<bytes.length;i++)text+=String.fromCharCode(bytes[i]);return decodeURIComponent(escape(text));}
  function utf8Encode(text){if(typeof TextEncoder!=="undefined")return new TextEncoder().encode(text);var encoded=unescape(encodeURIComponent(text)),out=new Uint8Array(encoded.length);for(var i=0;i<encoded.length;i++)out[i]=encoded.charCodeAt(i);return out;}
  function rotate(value,bits){return (value>>>bits)|(value<<(32-bits));}
  function sha256(data){var constants=[1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298];var length=data.length,total=Math.ceil((length+9)/64)*64,buffer=new Uint8Array(total),view=new DataView(buffer.buffer),bits=length*8;buffer.set(data);buffer[length]=128;view.setUint32(total-8,Math.floor(bits/4294967296));view.setUint32(total-4,bits>>>0);var hash=[1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225],words=new Uint32Array(64);for(var offset=0;offset<total;offset+=64){for(var i=0;i<16;i++)words[i]=view.getUint32(offset+i*4);for(i=16;i<64;i++){var s0=rotate(words[i-15],7)^rotate(words[i-15],18)^(words[i-15]>>>3),s1=rotate(words[i-2],17)^rotate(words[i-2],19)^(words[i-2]>>>10);words[i]=(words[i-16]+s0+words[i-7]+s1)>>>0;}var a=hash[0],b=hash[1],c=hash[2],d=hash[3],e=hash[4],f=hash[5],g=hash[6],h=hash[7];for(i=0;i<64;i++){var upper=rotate(e,6)^rotate(e,11)^rotate(e,25),choice=(e&f)^(~e&g),t1=(h+upper+choice+constants[i]+words[i])>>>0,lower=rotate(a,2)^rotate(a,13)^rotate(a,22),majority=(a&b)^(a&c)^(b&c),t2=(lower+majority)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0;}hash[0]=(hash[0]+a)>>>0;hash[1]=(hash[1]+b)>>>0;hash[2]=(hash[2]+c)>>>0;hash[3]=(hash[3]+d)>>>0;hash[4]=(hash[4]+e)>>>0;hash[5]=(hash[5]+f)>>>0;hash[6]=(hash[6]+g)>>>0;hash[7]=(hash[7]+h)>>>0;}var result=new Uint8Array(32),resultView=new DataView(result.buffer);for(i=0;i<8;i++)resultView.setUint32(i*4,hash[i]);return result;}
  function hmac256(key,data){if(key.length>64)key=sha256(key);var inner=new Uint8Array(64+data.length),outer=new Uint8Array(96);for(var i=0;i<64;i++){var value=i<key.length?key[i]:0;inner[i]=value^54;outer[i]=value^92;}inner.set(data,64);outer.set(sha256(inner),64);return sha256(outer);}
  function equal(a,b){if(!a||!b||a.length!==b.length)return false;var difference=0;for(var i=0;i<a.length;i++)difference|=a[i]^b[i];return difference===0;}
  function cleanPlayer(value,counts){if(!value||typeof value!=="object")return false;var changed=false,context=value.context;if(context&&typeof context==="object"&&Object.prototype.hasOwnProperty.call(context,"adSignalsInfo")){delete context.adSignalsInfo;counts.contextAdSignals++;changed=true;}var content=value.playbackContext&&value.playbackContext.contentPlaybackContext;if(content&&typeof content==="object"){var names=["adParams","forceAdParameters"];for(var i=0;i<names.length;i++)if(Object.prototype.hasOwnProperty.call(content,names[i])){delete content[names[i]];counts.playbackAdParams++;changed=true;}if(content.isInlinePlaybackNoAd!==true){content.isInlinePlaybackNoAd=true;counts.inlineNoAd++;changed=true;}}return changed;}
  function cleanEncryptedRequest(body,state){if(typeof $crypto==="undefined"||!$crypto.aes||typeof $crypto.aes.decrypt!=="function"||typeof $crypto.aes.encrypt!=="function")fail("crypto-unavailable");var root=bytesOf(body),budget={fields:0};if(!root||!root.length||root.length>MAX_BODY)fail("unsupported-body");var rootRecords=parse(root,budget),outer=only(rootRecords,3,2);if(!outer)return null;var envelope=root.subarray(outer.dataStart,outer.dataEnd),records=parse(envelope,budget),cipherField=only(records,2,2),ivField=only(records,6,2),macField=only(records,7,2);if(!cipherField||!ivField||!macField)fail("incomplete-encrypted-request");var clientKey=unbase64(state.clientKey);if(clientKey.length!==32)fail("invalid-client-key");var cipher=envelope.subarray(cipherField.dataStart,cipherField.dataEnd),iv=envelope.subarray(ivField.dataStart,ivField.dataEnd),mac=envelope.subarray(macField.dataStart,macField.dataEnd);if(iv.length!==16||mac.length!==32)fail("invalid-crypto-params");if(!equal(hmac256(clientKey.subarray(16),concat([cipher,iv])),mac))fail("hmac-mismatch");var plain=bytesOf($crypto.aes.decrypt(cipher,{mode:"ctr",key:clientKey.subarray(0,16),iv:iv}));if(!plain)fail("decrypt-failed");var innerRecords=parse(plain,budget),bodyField=only(innerRecords,3,2);if(!bodyField)return null;var value=JSON.parse(utf8Decode(plain.subarray(bodyField.dataStart,bodyField.dataEnd))),counts={contextAdSignals:0,playbackAdParams:0,inlineNoAd:0};if(!cleanPlayer(value,counts))return null;var encoded=utf8Encode(JSON.stringify(value)),innerParts=[];for(var i=0;i<innerRecords.length;i++)innerParts.push(innerRecords[i]===bodyField?message(3,encoded):raw(plain,innerRecords[i]));var cleanedPlain=concat(innerParts),encrypted=$crypto.aes.encrypt(cleanedPlain,{mode:"ctr",key:clientKey.subarray(0,16),iv:iv}),cleanedCipher=bytesOf(encrypted&&encrypted.ciphertext);if(!cleanedCipher||cleanedCipher.length!==cleanedPlain.length)fail("encrypt-failed");var cleanedMac=hmac256(clientKey.subarray(16),concat([cleanedCipher,iv])),envelopeParts=[];for(i=0;i<records.length;i++){var record=records[i];if(record===cipherField)envelopeParts.push(message(2,cleanedCipher));else if(record===macField)envelopeParts.push(message(7,cleanedMac));else if(record.no===13&&record.wire===0)envelopeParts.push(scalar(13,0));else envelopeParts.push(raw(envelope,record));}var cleanedEnvelope=concat(envelopeParts),rootParts=[];for(i=0;i<rootRecords.length;i++)rootParts.push(rootRecords[i]===outer?message(3,cleanedEnvelope):raw(root,rootRecords[i]));return{body:concat(rootParts),counts:counts};}
  function readState(){if(typeof $persistentStore==="undefined")return null;try{var raw=$persistentStore.read(STATE_KEY),state=raw&&raw.length<=8192?JSON.parse(raw):null;if(!state||state.schema!==1||state.platform!=="youtube"||typeof state.clientKey!=="string"||typeof state.encryptKey!=="string")return null;if(!Number.isFinite(state.expiresAt)||state.expiresAt<=Date.now()){$persistentStore.write(undefined,STATE_KEY);return null;}return state;}catch(_){return null;}}
  function clearState(){if(typeof $persistentStore!=="undefined")$persistentStore.write(undefined,STATE_KEY);}
  function rewrittenHeaders(headers){var result={},keys=Object.keys(headers||{});for(var i=0;i<keys.length;i++){var lower=keys[i].toLowerCase();if(lower!=="content-encoding"&&lower!=="content-length")result[keys[i]]=headers[keys[i]];}return result;}
  function utf8Size(text){return unescape(encodeURIComponent(text)).length;}
  function checksum(text){var hash=2166136261;for(var i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return "fnv1a32-utf16:"+("00000000"+(hash>>>0).toString(16)).slice(-8);}
  function captureBody(body){if(body===undefined||body===null)return{available:false,reason:"not-provided-by-runtime"};if(typeof body==="string")return{available:true,encoding:"utf8-text",bytes:utf8Size(body),data:body};var bytes=bytesOf(body);return bytes?{available:true,encoding:"base64",bytes:bytes.length,data:base64(bytes)}:{available:false,reason:"unsupported-runtime-body-type"};}
  function logConfig(){if(!flag(args.log_enabled)||typeof $persistentStore==="undefined")return null;try{var raw=$persistentStore.read(LOG_CONFIG),c=raw&&raw.length<=2048?JSON.parse(raw):null;return c&&c.enabled===true&&typeof c.session==="string"&&/^[a-z0-9-]{1,80}$/.test(c.session)?c:null;}catch(_){return null;}}
  function append(entry,payload){var c=logConfig(),written=[];if(!c)return false;try{var raw=$persistentStore.read(LOG_CACHE),old=raw?JSON.parse(raw):null,state=old&&old.session===c.session&&Array.isArray(old.entries)?old:{session:c.session,entries:[],captureBytes:0};if(state.entries.length>=600)return false;var serialized=payload?JSON.stringify(payload):null,size=serialized?utf8Size(serialized):0,budget=[16,32,64].indexOf(Number(args.capture_budget))>=0?Number(args.capture_budget)*1048576:33554432;if((state.captureBytes||0)+size>budget||size>33554432)return false;if(serialized){var chunks=[];for(var start=0;start<serialized.length;start+=131072)chunks.push(serialized.slice(start,start+131072));if(chunks.length>256)return false;var prefix="ytads.capture."+c.session+"."+payload.id+".";entry.captureRef={prefix:prefix,chunks:chunks.length,chars:serialized.length,storedBytes:size,checksum:checksum(serialized)};for(var i=0;i<chunks.length;i++){var key=prefix+i;if($persistentStore.write(chunks[i],key)!==true)fail("capture-write-failed");written.push(key);}}var next={session:c.session,entries:state.entries.concat([entry]),captureBytes:(state.captureBytes||0)+size},index=JSON.stringify(next);if(utf8Size(index)>131072||$persistentStore.write(index,LOG_CACHE)!==true)fail("index-write-failed");return true;}catch(_){for(var j=0;j<written.length;j++)try{$persistentStore.write(undefined,written[j]);}catch(_){}return false;}}
  function record(message,level,output){var now=new Date().toISOString(),changed=!!(output&&(output.response||output.body));if(flag(args.capture_raw)){var id=Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,14),request={url:$request.url,method:$request.method||"GET",headers:$request.headers||{},h2_trailers:$request.h2_trailers||{},body:captureBody($request.body)};var payload={schema:1,id:id,time:now,source:SOURCE,version:VERSION,phase:"request",endpoint:"initplayback",runtime:typeof $loon==="string"?$loon:null,correlation:{urlMethodHash:checksum(request.method+" "+request.url),exactPairing:false},request:request,processing:{exception:null,executionScript:SOURCE,elapsedMs:0,messages:[message],arguments:{onesie_enabled:enabled,onesie_refresh_on_mismatch:refreshMismatch,log_level:args.log_level||"info"}},responseAfter:output&&output.response?{synthetic:true,status:output.response.status,headers:output.response.headers,body:captureBody(output.response.body)}:null,requestAfter:output&&output.body?{changed:true,body:captureBody(output.body)}:null};append({source:SOURCE,version:VERSION,endpoint:"initplayback",level:"debug",time:now,phase:"request",message:"development capture: changed="+changed},payload);}else{var ranks={debug:0,info:1,warn:2,error:3},minimum=Object.prototype.hasOwnProperty.call(ranks,args.log_level)?args.log_level:"info";if(ranks[level]>=ranks[minimum])append({source:SOURCE,version:VERSION,endpoint:"initplayback",level:level,time:now,phase:"request",message:message},null);}if(debug&&typeof console!=="undefined")console.log("["+SOURCE+" "+VERSION+"] initplayback "+message);}

  var output = {};
  if (enabled && typeof $request !== "undefined" && typeof $response === "undefined" && API.test($request.url || "") && isYouTubeApp()) {
    try {
      var state = readState(), key = encryptedClientKey($request.body);
      if (!key || !key.length) record("pass: encrypted client key absent", "debug", output);
      else if (!state) record("pass: active config absent", "info", output);
      else if (base64(key) === state.encryptKey) {
        var cleaned = cleanEncryptedRequest($request.body, state);
        if (cleaned) {
          output = {headers:rewrittenHeaders($request.headers),body:cleaned.body};
          record("changed: authenticated=true context_ad_signals=" + cleaned.counts.contextAdSignals + " playback_ad_params=" + cleaned.counts.playbackAdParams + " inline_no_ad=" + cleaned.counts.inlineNoAd, "info", output);
        } else record("matched: local config active; inner player request unchanged", "debug", output);
      }
      else {
        clearState();
        if (refreshMismatch) output = {response:{status:200,headers:{"Content-Type":"application/x-protobuf","Cache-Control":"no-store"},body:new Uint8Array(0)}};
        record("mismatch: config cleared refresh=" + refreshMismatch, "warn", output);
      }
    } catch (error) { record("pass: " + (error && error.message || "parse-failed"), "warn", output); output = {}; }
  }
  $done(output);
})();
